###
get http://localhost:9900/uplay/checkAuth
content-type: application/json

###
post http://localhost:9900/uplay/register
content-type: application/json

{
    "username": "asdasdads",
    "password": "dasdasads@",
    "email": "yse",
    "profile_image": "asdasdasd..."
}